### ISSUE TITLE
Build failed when i use target sdk 31

### ISSUE THREAD

**Issue by syntaxxxxx** [android-actions/setup-android#233]
i got error in github actions Execution failed for task ':app:kaptStgDebugKotlin
anyone can help me fix this issue?
thank you

**Comment by ViliusSutkus89** [comment]
Hello. Is the app compiling OK when do you a clean build on your computer?

**Comment by rustyhamsterr** [comment]
Hi,
currently I am facing this problem as well and yes clean build works on my local machine.

Any Ideas? :D
Thanks in advance

**Comment by syntaxxxxx** [comment]
hi niels

thank you for your reply

there's no trouble in my local

but when i build on github actions, failed

**Comment by ViliusSutkus89** [comment]
Works for me. Show the failing github actions run.

**Comment by ViliusSutkus89** [comment]
Let me know if we should circle back here
