### ISSUE TITLE
Error on Expand 

### ISSUE THREAD

**Issue by joeserhtf** [android-actions/setup-android#305]
Hello, I'm unable to run this action on self hosted windows, get this message every time and can't figure out why. Somebody knows about ?

![image](https://user-images.githubusercontent.com/26913926/174500340-971c0acf-1d58-454b-9f1a-4391cf8ea400.png)

**Comment by AceCoderLaura** [comment]
Looks like a duplicate of #369

**Comment by ViliusSutkus89** [comment]
Yes, it's an exact same issue, exact same error, but in different language. Closing as duplicate
