### ISSUE TITLE
Deprecated GitHub actions usage

### ISSUE THREAD

**Issue by TWiStErRob** [android-actions/setup-android#355]
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Example: https://github.com/TWiStErRob/glide-support/actions/runs/3275044365/jobs/5389377582#step:3:710

Similar fix: https://github.com/actions/checkout/pull/962/files#diff-321508dc4e9600826d25995a75796331f7015f0faeaea651daf659bf3e8a98f6L46

**Comment by TWiStErRob** [comment]
Will be solved by https://github.com/android-actions/setup-android/pull/347, because you only use `setOutput`.

**Comment by TWiStErRob** [comment]
Confirmed fixed! Re-ran the the job I quoted above on the same commit.

Before:
https://github.com/TWiStErRob/glide-support/actions/runs/3275044365/jobs/5389377582#step:3:710
![image](https://user-images.githubusercontent.com/2906988/196546890-e27ce0de-0cd6-42a7-80b4-1f90df7a78da.png)

After:
https://github.com/TWiStErRob/glide-support/actions/runs/3275044365/jobs/5393688733#step:3:708
![image](https://user-images.githubusercontent.com/2906988/196546980-2d569831-edfa-4dec-ad8c-140122e70936.png)

Thanks for the amazing turnaround.

**Comment by ViliusSutkus89** [comment]
No need to thank me, that warning would have turned into an error eventually. Now I need to find 20+ different places in other projects where I use set-output manually

**Comment by TWiStErRob** [comment]
Not much: https://github.com/search?q=user%3AViliusSutkus89+set-output&type=code

Example that might help (if you have non-trivial echo): https://github.com/TWiStErRob/net.twisterrob.sun/pull/156

**Comment by kyhule** [comment]
Should I be surprised to still see this error on v2.0.2?
<img width="843" alt="CleanShot 2023-02-22 at 17 07 03@2x" src="https://user-images.githubusercontent.com/2845460/220770807-ccf83aa0-2549-4074-9b1a-111de4f8f969.png">

**Comment by TWiStErRob** [comment]
Weird the only usage is here:
https://github.com/android-actions/setup-android/blame/main/src/main.ts#L184
And that's still a valid usage, because the actions/core dependency is 1.10.0, bumped by #347

@ViliusSutkus89 is it possible you didn't do `npm install` at one point when you rebuild the dist?

**Comment by TWiStErRob** [comment]
I have a recent execution on v2
https://github.com/TWiStErRob/net.twisterrob.sun/actions/runs/4247851865/jobs/7386353596#step:4:8, no warnings.

**Comment by TWiStErRob** [comment]
@kyhule 2.0.2 is really old, the fix only exists in 2.0.10:
https://github.com/android-actions/setup-android/tags

**Comment by kyhule** [comment]
@TWiStErRob Ah sorry about that. This is the first time using GitHub actions. I was using v2.0.2 because that is the version listed as the latest on the actions marketplace. I'll upgrade to v2.0.10 today!
![Screenshot_20230223-080443.png](https://user-images.githubusercontent.com/2845460/220914759-d01f015e-24b4-4ca9-aeb4-042b2a679418.png)

**Comment by TWiStErRob** [comment]
I recommend you just use `@v2`, then this is not a problem. @ViliusSutkus89 any idea what's missing for recent versions to show up at https://github.com/marketplace/actions/setup-android-sdk-tools?
