### ISSUE TITLE
Using this action together with AGP Hedgehog causes a 5-10x slowdown

### ISSUE THREAD

**Issue by eygraber** [android-actions/setup-android#394]
When using this action in a project that is using AGP Hedgehog, builds slow down by a factor of 5-10x. I'm assuming this is because old versions of tools are being forced onto the PATH.

**Comment by ViliusSutkus89** [comment]
Could you check if current update solved it?

**Comment by ViliusSutkus89** [comment]
I'm pretty sure it did solve it. Closing the issue, let me know if we should reopen
