### ISSUE TITLE
Missing versions on GitHub marketplace

### ISSUE THREAD

**Issue by TWiStErRob** [android-actions/setup-android#395]
As pointed out in https://github.com/android-actions/setup-android/issues/355#issuecomment-1441746705 there are many missing versions:

| Marketplace | Releases |
| - | - |
| ![image](https://github.com/android-actions/setup-android/assets/2906988/85cb5130-2b83-445a-a481-0128b4a1e651) | ![image](https://github.com/android-actions/setup-android/assets/2906988/127cabda-f405-46ea-be28-8596e6176ec1) |

I think the missing piece is pressing this checkbox when releasing. This is probably doable just by editing the past releases to bump them into the marketplace too.

![image](https://github.com/android-actions/setup-android/assets/2906988/b0072468-db32-41a6-9ef8-be40fa792bb7)

**Comment by bkonicek-calm** [comment]
Good catch! I initially set this up from the marketplace and it threw some really confusing errors trying to install the SDK. Bumping it to v3 solved it for me

**Comment by ViliusSutkus89** [comment]
I can't publish on GitHub marketplace. I believe @daveol has repository admin rights to accept the GitHub marketplace developer agreement

![image](https://github.com/android-actions/setup-android/assets/812793/67c79aa6-ec5b-43e0-8686-f8fa2e41f8d9)

**Comment by daveol** [comment]
Done

**Comment by ViliusSutkus89** [comment]
@daveol , hello mate, sorry for the late reply. Could you do it again? There was a timer on my part and I wasn't very online that week, so I missed it.

**Comment by ViliusSutkus89** [comment]
@daveol thanks mate

**Comment by ViliusSutkus89** [comment]
v3.1.0 available in GitHub Marketplace - https://github.com/marketplace/actions/setup-android-sdk-tools?version=v3.1.0

**Comment by ViliusSutkus89** [comment]
Yeah, that makes sense. Haven't even tried using v2.0.0 or v1.0.0, so not adding those, but every other later version is already on Marketplace

**Comment by TWiStErRob** [comment]
Nice!, Note: 2.0.10 (latest 2.x) is not showing in the dropdown for me.

**Comment by ViliusSutkus89** [comment]
Yes, indeed it was missing. Fixed now.

That drop down list is not ordered numerically, so v2.0.10 is at the bottom, below v2.0.2 and also v2.0.1 and v2.0.0 are missing, no idea why, because they are in the marketplace

![image](https://github.com/android-actions/setup-android/assets/812793/8bd6c5d1-3374-43ab-a4cc-4b1467b65090)

**Comment by TWiStErRob** [comment]
Thanks! 🤦🏻‍♂️ ok, the ordering is fun...
