### ISSUE TITLE
CMAKE toolchain file

### ISSUE THREAD

**Issue by rickomax** [android-actions/setup-android#494]
How to install the CMAKE toolchain files using this action?

**Comment by ViliusSutkus89** [comment]
Install it using sdkmanager:
```yaml
- uses: android-actions/setup-android@v3

- run: sdkmanager "cmake;3.30.5"
```

**Comment by rickomax** [comment]
> Install it using sdkmanager:
> 
> ```yaml
> - uses: android-actions/setup-android@v3
> 
> - run: sdkmanager "cmake;3.30.5"
> ```

this worked. tysm!
